---
- name: Installer et configurer MariaDB
  hosts: all
  become: yes
  tasks:
    - name: Installation de MariaDB
      apt:
        name: mariadb-server
        state: latest

    - name: Démarrage et activation du service MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes
