version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    networks:
      - iproxy

networks:
  iproxy:
    name: iproxy
    external: true