#!/bin/bash
### BEGIN INIT INFO
# Provides:          vm-proxmox
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: VM Proxmox FastAPI Service
### END INIT INFO

# sudo cp vm_proxmox_service /etc/init.d/vm-proxmox
# sudo chmod +x /etc/init.d/vm-proxmox
# sudo update-rc.d vm-proxmox defaults
# sudo service vm-proxmox start/stop/status/restart


# Configuration
APP_DIR=/home/z1/vm-proxmox
APP_SCRIPT=main.py
APP_HOST=0.0.0.0
APP_PORT=8000
APP_USER=z1
APP_GROUP=z1
UVICORN_PATH=/home/z1/vm-proxmox/venv/bin/uvicorn

# Fonctions
start() {
    echo "Starting VM Proxmox service..."
    cd $APP_DIR
    sudo -u $APP_USER -g $APP_GROUP $UVICORN_PATH main:app --host $APP_HOST --port $APP_PORT >> /var/log/vm-proxmox_service.log 2>&1 &
    echo "VM Proxmox service started."
}

stop() {
    echo "Stopping VM Proxmox service..."
    local pid=$(ss -lptn "sport = :$APP_PORT" | grep -Po 'pid=\K\d+' | head -1)
    if [ ! -z "$pid" ]; then
        kill -15 $pid
        echo "VM Proxmox service stopped."
    else
        echo "No VM Proxmox service found running on port $APP_PORT."
    fi
}

status() {
    if ss -lptn "sport = :$APP_PORT" | grep -q ":$APP_PORT"; then
        echo "VM Proxmox service is running."
    else
        echo "VM Proxmox service is not running."
    fi
}

restart() {
    echo "Restarting VM Proxmox service..."
    stop
    sleep 2 
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
